#**Numpy tutorial**

we will learn creating arrays , using random function , indexing arrays , slicing arrays , statistical and mathematical functions and practical working.

We will do some operations on real world datasets which we will import from kaggle.

In [ ]:
import numpy as np # np is the alias


arr = np.array([1,2,3,4,5]) # 1 dimensional or 1-D array
print(arr)
print(type(arr)) # checking the type of the variable
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]]) # 2-D array
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]) # 3-D array
print(arr2d)
print(type(arr2d))
print(arr3d)
print(type(arr3d))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [ ]:
print(np.shape(arr)) # getting shapes ---> rows x columns
print(np.shape(arr2d)) # shape of 2-D array
print(np.shape(arr3d))


(5,)
(2, 3)
(2, 3, 3)


In [ ]:
arrn = np.reshape(arr,(5,1)) # know this that even shape of arra was shown as (5,) but actually it was in the format of
# (1,5) which means a single row and 5 columns and here we reversed the order of the matrix
print(arrn)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
arrn2d = np.reshape(arr3d,(9,-1)) # we converted this 3-D arr3d array into a new 2-D array. you can skip one of the shape values as -1 and reshape will calculate the value of that place automatically.
# but you can't leave more than one shape value as -1
print(arrn2d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
mat = np.random.rand(3,3,3) # this is use of random function where we generate random inputs of elements for a predefined shape of array.
# THe elements always range from 0 to 1 both being exclusive.
print(mat)


[[[4.33589787e-01 5.80848263e-01 8.21735557e-02]
  [3.77735006e-01 7.63282611e-01 5.82729985e-01]
  [5.73352502e-01 3.08845441e-01 1.44843926e-01]]

 [[3.19325196e-01 4.61260000e-01 6.47112704e-01]
  [3.87428920e-01 7.14749299e-02 4.59667889e-01]
  [3.73470683e-01 1.12550423e-04 8.73250830e-01]]

 [[8.91259043e-01 8.30250333e-01 8.58998982e-01]
  [8.75472742e-01 5.82356469e-01 9.90595002e-02]
  [1.35495955e-01 1.82007612e-01 5.47427969e-01]]]


In [ ]:
mat1 = np.random.rand(3,3,3) # as u can see we ran the same piece of code with new name and the elements are different
# if you run this or previous block , the array will change again
print(mat)


[[[4.33589787e-01 5.80848263e-01 8.21735557e-02]
  [3.77735006e-01 7.63282611e-01 5.82729985e-01]
  [5.73352502e-01 3.08845441e-01 1.44843926e-01]]

 [[3.19325196e-01 4.61260000e-01 6.47112704e-01]
  [3.87428920e-01 7.14749299e-02 4.59667889e-01]
  [3.73470683e-01 1.12550423e-04 8.73250830e-01]]

 [[8.91259043e-01 8.30250333e-01 8.58998982e-01]
  [8.75472742e-01 5.82356469e-01 9.90595002e-02]
  [1.35495955e-01 1.82007612e-01 5.47427969e-01]]]


In [ ]:
state = np.random.RandomState(21) # here we state a random state , which means we are storing this session and when we use
# this random state again , you will get the same array as this one.
# The number 21 can be replaced with any number as per your wish , but when u want to get the same sample you need to set
# the same number again
mat2 = np.random.rand(3,3,3)
print(mat)

[[[4.33589787e-01 5.80848263e-01 8.21735557e-02]
  [3.77735006e-01 7.63282611e-01 5.82729985e-01]
  [5.73352502e-01 3.08845441e-01 1.44843926e-01]]

 [[3.19325196e-01 4.61260000e-01 6.47112704e-01]
  [3.87428920e-01 7.14749299e-02 4.59667889e-01]
  [3.73470683e-01 1.12550423e-04 8.73250830e-01]]

 [[8.91259043e-01 8.30250333e-01 8.58998982e-01]
  [8.75472742e-01 5.82356469e-01 9.90595002e-02]
  [1.35495955e-01 1.82007612e-01 5.47427969e-01]]]


In [ ]:
state = np.random.RandomState(21) # this code is proof of the previous claim
mat3 = np.random.rand(3,3,3)
print(mat)


[[[4.33589787e-01 5.80848263e-01 8.21735557e-02]
  [3.77735006e-01 7.63282611e-01 5.82729985e-01]
  [5.73352502e-01 3.08845441e-01 1.44843926e-01]]

 [[3.19325196e-01 4.61260000e-01 6.47112704e-01]
  [3.87428920e-01 7.14749299e-02 4.59667889e-01]
  [3.73470683e-01 1.12550423e-04 8.73250830e-01]]

 [[8.91259043e-01 8.30250333e-01 8.58998982e-01]
  [8.75472742e-01 5.82356469e-01 9.90595002e-02]
  [1.35495955e-01 1.82007612e-01 5.47427969e-01]]]


#**Create an array of zeros of given shape**

np.zeros(): create array of all zeros in given shape

np.zeros_like(): create array of all zeros with the same shape and data type as the given input array

Simillarlly you can use np.ones and np.empty to create srrays of ones and empty array respectively.

In [ ]:
zeros = np.zeros((2,3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64) # we are initially telling that elements inside this array should be
# of complex data type
zeros = np.zeros_like(arr)
print(zeros)
print(type(zeros.dtype))
print('Data Type: ' + str(zeros.dtype)) # we used type casting here

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
<class 'numpy.dtype[complex64]'>
Data Type: complex64


#**arange function**

this function will help us to directly generate a 1-D array with elements in a specified range

In [ ]:
A = np.arange(1,10) # 1 will inclusive and 10 will exclusive
A


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#**Create an identity matrix of given size**

np.eye(size, k=0): create an identity matrix of given size

size: the size of the identity matrix

k: the diagonal offset

np.identity(): same as np.eye() but does not carry parameters

In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


#**Stacking of arrays**

Stacking means concatinating the elements of two arrays of compatible size , vertically or horizontally

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2)) # Horizontal Stacking of Numpy Arrays

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2)) # Vertically Stacking of Numpy Arrays

print(o)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


#**Mathematics in numpy**

you can perfom basic operations on the arrays like addition of a number to all the elements , multiplying a constant to all the elements , giving array as argument to functions like , sin() , cos() , sqrt() , log()

In [ ]:
arr = np.random.rand(5,5)
arr


array([[0.10400345, 0.42224337, 0.6200716 , 0.13148485, 0.34565281],
       [0.1569135 , 0.39410388, 0.89861877, 0.07042376, 0.27861765],
       [0.96078858, 0.82300661, 0.06463098, 0.1978123 , 0.86194597],
       [0.97062868, 0.09314047, 0.09812688, 0.17522479, 0.90505425],
       [0.83434482, 0.00425548, 0.04664573, 0.07485515, 0.33734323]])

In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.10400345 10.42224337 10.6200716  10.13148485 10.34565281]
 [10.1569135  10.39410388 10.89861877 10.07042376 10.27861765]
 [10.96078858 10.82300661 10.06463098 10.1978123  10.86194597]
 [10.97062868 10.09314047 10.09812688 10.17522479 10.90505425]
 [10.83434482 10.00425548 10.04664573 10.07485515 10.33734323]]
[[-9.89599655 -9.57775663 -9.3799284  -9.86851515 -9.65434719]
 [-9.8430865  -9.60589612 -9.10138123 -9.92957624 -9.72138235]
 [-9.03921142 -9.17699339 -9.93536902 -9.8021877  -9.13805403]
 [-9.02937132 -9.90685953 -9.90187312 -9.82477521 -9.09494575]
 [-9.16565518 -9.99574452 -9.95335427 -9.92514485 -9.66265677]]
[[1.04003448 4.22243369 6.20071604 1.3148485  3.45652812]
 [1.56913498 3.94103882 8.98618766 0.70423758 2.78617654]
 [9.60788581 8.2300661  0.64630978 1.978123   8.61945965]
 [9.70628676 0.93140474 0.98126876 1.75224785 9.05054252]
 [8.34344821 0.04255481 0.46645726 0.7485515  3.37343233]]
[[0.01040034 0.04222434 0.06200716 0.01314848 0.03456528]
 [0.01569135 0.0394

In [ ]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)


[ 9 11 13]
[1 2 3]
[1 4 9]


In [ ]:
print(np.exp(arr)) # exponetial function of arr
# natural log
print(np.log(arr))
print()
# base 2
print(np.log2(arr))
print()
# base 10
print(np.log10(arr))
print()
# elementwise sin(arr)
print(np.sin(arr))
print()
# elementwise square root
print(np.sqrt(arr))

[[1.10960428 1.52537971 1.85906115 1.14052063 1.41291198]
 [1.16989441 1.4830546  2.45620817 1.07296276 1.32130205]
 [2.61375682 2.27733662 1.06676529 1.21873362 2.3677638 ]
 [2.63960339 1.09761591 1.10310273 1.19151402 2.47206603]
 [2.30330448 1.00426455 1.04775075 1.07772803 1.40121993]]
[[-2.26333123 -0.86217343 -0.47792032 -2.02886364 -1.06232044]
 [-1.85206059 -0.93114074 -0.1068964  -2.65322461 -1.27791485]
 [-0.04000089 -0.19479105 -2.73906144 -1.62043668 -0.1485627 ]
 [-0.0298113  -2.37364645 -2.32149398 -1.74168564 -0.09976039]
 [-0.18110851 -5.45954758 -3.06517398 -2.59220037 -1.08665437]]

[[-3.26529674 -1.24385333 -0.68949327 -2.92703152 -1.53260443]
 [-2.67195863 -1.34335213 -0.1542189  -3.82779398 -1.84364142]
 [-0.05770909 -0.28102408 -3.95163036 -2.33779596 -0.21433066]
 [-0.04300861 -3.42444797 -3.34920786 -2.51272124 -0.14392382]
 [-0.26128435 -7.87646223 -4.4221113  -3.73975462 -1.56771087]]

[[-0.98295226 -0.37443716 -0.20755816 -0.88112429 -0.46135991]
 [-0.8043397

#**Matrix as a NumPy array**

Everything in NumPy is an array. A matrix is also an array. Let us create a simple matrix:


In NumPy:

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)  #Adding two matrices


[[ 6  8]
 [10 12]]


In [ ]:
A = np.arange(1,10).reshape(3,3)
print(3*A)  #Scaling a matrix is nothing but element-wise multiplication:

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A*B) #Element-wise multiplication of matrices


[[ 5 12]
 [21 32]]


In [ ]:
A = np.array([[1 , np.sqrt(2)],[np.sqrt(3),2]]) # np.sqrt() is a mathematical tool for square root of a number
B = A**2
print(B) # using np.sqrt() will convert the values inside the matrix into float type by default.

[[1. 2.]
 [3. 4.]]


In [ ]:
M = np.array([[1,2,3],[4,5,6]])
y = np.transpose(M)
y  #Transpose of a matrix


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
y = M.T # better option than np.transpose
y

array([[1, 4],
       [2, 5],
       [3, 6]])

#**Products involving matrices and vectors**

We will look at the following products:

matrix - matrix

matrix - vector

vector - matrix

vector - vector

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
A @ B #Product of two matrices

array([[ 58,  64],
       [139, 154]])

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([6,7,8])
A @ X # here even if you don't give the transposed matrix , it will automatically do the transpose and give you the ccorrect #Product of a matrix and a (column) vector

array([ 44, 107, 170])

In [ ]:
#(Inner) Product of a (row) vector and a (column) vector
#The product of a row vector and a column vector is nothing but the usual dot product
# you can again use @ here , it will give you the required answer

#**Indexing and Slicing**

Just like lists in Python, NumPy arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

In [ ]:
V = np.arange(1,11) # it can't shape a 1-D array of prime number of elements to any new shape.
V = V.reshape(5,2) # will make our life simpler by converting an array to required shape.
# if you set any one parameter to -1 in reshape() funtion will automatically compute the valid value of that particular parameter.
V #Row-slice

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
print(V[2]) #for rows you can just simply apply the logic of list indexing method to get your answer.


[5 6]


In [ ]:
V = np.arange(1,10).reshape(3,3) # you can attach two functions to make your code shorter.
V #Column slice


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(V[1,2]) # this simply means traversing to 2nd row and 3rd column
print(V[:,1]) # adding a colon means getting all the elements related to that parameter.

6
[2 5 8]


In [ ]:
V = np.arange(1,17).reshape(4,4)
V #Submatrix slice


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# In line 22 , we just used 1 number for input in row and column , but we can give a series
# of rows and columns as input which will enable us to use submatrix slice

V[1:3 , 2:4] #here we used '1:3' to specify that we wan't 2nd to 3rd row. we used '2:4' to
# specify that we want from column 3 to 4 . And hence u can see the result.

array([[ 7,  8],
       [11, 12]])

#**Matrix algebra**

There are several important matrix operations that we will list down here. The np.linalg module helps us perform these operations effortlessly.

**Rank, Inverse**


In [ ]:
V[1,2]=22  # changed an element in previous matrix , as that was a singular matrix , whose inverse is not possible.

# rank

print(np.linalg.matrix_rank(V))

# inverse

print(np.linalg.inv(V))

3
[[ 3.75299969e+14 -6.66666667e-02 -1.12589991e+15  7.50599938e+14]
 [-5.62949953e+14  6.66666667e-02  1.68884986e+15 -1.12589991e+15]
 [-5.55555556e-02  6.66666667e-02  3.33333333e-02 -4.44444444e-02]
 [ 1.87649984e+14 -6.66666667e-02 -5.62949953e+14  3.75299969e+14]]


In [ ]:
M = np.array([[1,2,3],[3,6,9]])
print(np.linalg.matrix_rank(M))
print(np.linalg.pinv(M)) # pseudo-inverse

1
[[0.00714286 0.02142857]
 [0.01428571 0.04285714]
 [0.02142857 0.06428571]]


In [ ]:
M = np.array([[1,0,-3],[0,5,2],[-3,2,8]])

eigen_values , eigen_vector = np.linalg.eigh(M) # linal.eigh() returns two values , the 1st one is eigne values and 2nd is corresponding eigen vectors.

print(eigen_values , eigen_vector) #EIGEN VALUES , EIGEN VECTORS


[-0.20942046  4.36588492  9.84353554] [[ 0.91805853  0.26010485 -0.2991889 ]
 [-0.14209114  0.92042494  0.36418131]
 [ 0.37010626 -0.29182767  0.88196257]]
